services:
  postgres:
    image: postgres:15-alpine
    container_name: aesthetic_db
    environment:
      POSTGRES_USER: aesthetic_user
      POSTGRES_PASSWORD: aesthetic_password
      POSTGRES_DB: aesthetic_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
